stages:
- build

images:
  stage: build
  script:
  - UPDATE_DOCKERHUB_SCRIPT=$(nix-build --no-out-link -QA updateDockerHubScript --argstr imageBaseName "$DOCKER_REPO" ./release.nix)
  - |
    if [ -n "${DOCKER_USERNAME}" ] && [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKERHUB_USERNAME}" ] && [ -n "${DOCKERHUB_PASSWORD}" ]
    then
      $UPDATE_DOCKERHUB_SCRIPT
    fi
  tags:
  - coinmetrics-nix-build-runner
