stages:
- build

images:
  stage: build
  script:
  - $(nix-build --no-out-link -QA updateDockerHubScript --argstr imageBaseName "$DOCKER_REPO" ./release.nix)
  tags:
  - coinmetrics-nix-build-runner
  only:
  - master

images-mr:
  stage: build
  script:
  - nix-build --no-out-link -QA updateDockerHubScript --argstr imageBaseName "$DOCKER_REPO" ./release.nix
  tags:
  - coinmetrics-nix-build-runner
  only:
  - merge_requests
